# Generated by Django 3.1.2 on 2020-11-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cnumber', models.IntegerField()),
                ('cemail', models.EmailField(max_length=254)),
                ('caddress', models.CharField(max_length=1000)),
                ('cservice', models.CharField(max_length=20)),
                ('cprice', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
