# Generated by Django 3.1.2 on 2020-11-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201110_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentorder',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
    ]
