# Generated by Django 3.1.2 on 2020-11-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_currentorder_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentorder',
            name='order_id',
        ),
    ]
